apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  strategy:          
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: us-west1-docker.pkg.dev/fluted-factor-438905-d2/azure-repo/backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "rootpassword"
            - name: DB_NAME
              value: "myapp"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3


          # env:
          #   - name: DB_HOST
          #     value: "mysql"
          #   - name: DB_USER
          #     value: "root"
          #   - name: DB_PASSWORD
          #     value: "{{ .Values.mysql.rootPassword }}"
          #   - name: DB_NAME
          #     value: "{{ .Values.mysql.database }}"
