apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: us-west1-docker.pkg.dev/fluted-factor-438905-d2/messenger-repo/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "https://messenger.example.com/api"
