frontend:
  image:
    repository: us-west1-docker.pkg.dev/fluted-factor-438905-d2/messenger-repo/frontend
    tag: "latest"
  service:
    port: 80

backend:
  image:
    repository: us-west1-docker.pkg.dev/fluted-factor-438905-d2/messenger-repo/backend
    tag: "latest"
  service:
    port: 5000
  env:
    DB_HOST: db
    DB_USER: root
    DB_PASSWORD: rootpassword
    DB_NAME: myapp

mysql:
  image: mysql:8.0
  rootPassword: rootpassword
  database: myapp
  service:
    port: 3306

ingress:
  enabled: true
  className: "gce"
  host: messenger.example.com
